### ISSUE TITLE
API gives super weird errors

### ISSUE THREAD

**Issue by jaspermayone** [hackclub/cdn#6]

**Comment by jaspermayone** [comment]
![CleanShot 2024-05-04 at 20 37 09@2x](https://github.com/hackclub/cdn/assets/65788728/36bdc24d-0d83-40f3-8db9-93e98358318d)

**Comment by cjdenio** [comment]
The "API doesn't work" issue was patched by 8d073b0! For clients that don't support redirect following, you can get around the original issue by calling https://cdn.hackclub.com/api/v1/new directly
